{{- if .Values.mysql.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "{{ .Release.Name }}-dmp-mysql-pv"
spec:
  capacity:
    storage: {{ .Values.mysql.size }}
  accessModes:
   - ReadWriteOnce
#  nfs:
#    path: /data/nfs/helm
#    server: 192.168.56.201
# TODO: currently support hostPath only.
  hostPath:
    path: /dmp-mysql
    type: DirectoryOrCreate
{{- end }}

