apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-dmp-user-center"
spec:
  type: {{ .Values.dmp.userCenter.service.type }}
  ports:
    - port: 9050
      name: usercenter
  selector:
    dx.daocloud.io/service-name: dmp-user-center
