apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-dmp-fate"
spec:
  type: {{ .Values.dmp.fate.service.type }}
  ports:
    - port: 9056
  selector:
    dx.daocloud.io/service-name: dmp-fate
